#############################################################################
# Makefile for building: pycam
# Generated by qmake (3.1) (Qt 5.9.2)
# Project:  src/pycam.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile src/pycam.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -Isrc -I. -Isrc -Isrc/Gui -Isrc/Geometry -Isrc/Importers -Isrc/Cutters -Isrc/PathGenerators -Isrc/PathProcessors -Isrc/Exporters -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild -isystem /usr/include/libdrm -Ibuild -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = pycam1.0.0
DISTDIR = /data/projects/pycam/build/pycam1.0.0
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -lGLU -lQt5OpenGL -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/pycam.cpp \
		src/Gui/dlgcuttersize.cpp \
		src/Gui/MainWindow.cpp \
		src/Gui/GLWidget.cpp \
		src/Gui/PreferencesDialog.cpp \
		src/Gui/StockModelDialog.cpp \
		src/Gui/ResizeModelDialog.cpp \
		src/Gui/AlignModelDialog.cpp \
		src/Gui/RotateModelDialog.cpp \
		src/Geometry/Geometry.cpp \
		src/Geometry/Boxed.cpp \
		src/Geometry/Stock.cpp \
		src/Geometry/Model.cpp \
		src/Geometry/Path.cpp \
		src/Geometry/HeightField.cpp \
		src/Geometry/TestModel.cpp \
		src/Utils/polynomials.cpp \
		src/Importers/STLImporter.cpp \
		src/Cutters/Cutter.cpp \
		src/Cutters/BaseCutter.cpp \
		src/Cutters/CylindricalCutter.cpp \
		src/Cutters/SphericalCutter.cpp \
		src/PathGenerators/DropCutter.cpp \
		src/PathGenerators/SimpleCutter.cpp \
		src/PathProcessors/PathProcessors.cpp \
		src/Exporters/GCodeExporter.cpp \
		src/Exporters/STLExporter.cpp \
		src/Tests/TestRunner.cpp build/qrc_pycam.cpp \
		build/moc_AboutDialog.cpp \
		build/moc_dlgcuttersize.cpp \
		build/moc_MainWindow.cpp \
		build/moc_GLWidget.cpp \
		build/moc_PreferencesDialog.cpp \
		build/moc_StockModelDialog.cpp \
		build/moc_ResizeModelDialog.cpp \
		build/moc_AlignModelDialog.cpp \
		build/moc_RotateModelDialog.cpp \
		build/moc_SimpleCutterDialog.cpp
OBJECTS       = build/pycam.o \
		build/dlgcuttersize.o \
		build/MainWindow.o \
		build/GLWidget.o \
		build/PreferencesDialog.o \
		build/StockModelDialog.o \
		build/ResizeModelDialog.o \
		build/AlignModelDialog.o \
		build/RotateModelDialog.o \
		build/Geometry.o \
		build/Boxed.o \
		build/Stock.o \
		build/Model.o \
		build/Path.o \
		build/HeightField.o \
		build/TestModel.o \
		build/polynomials.o \
		build/STLImporter.o \
		build/Cutter.o \
		build/BaseCutter.o \
		build/CylindricalCutter.o \
		build/SphericalCutter.o \
		build/DropCutter.o \
		build/SimpleCutter.o \
		build/PathProcessors.o \
		build/GCodeExporter.o \
		build/STLExporter.o \
		build/TestRunner.o \
		build/qrc_pycam.o \
		build/moc_AboutDialog.o \
		build/moc_dlgcuttersize.o \
		build/moc_MainWindow.o \
		build/moc_GLWidget.o \
		build/moc_PreferencesDialog.o \
		build/moc_StockModelDialog.o \
		build/moc_ResizeModelDialog.o \
		build/moc_AlignModelDialog.o \
		build/moc_RotateModelDialog.o \
		build/moc_SimpleCutterDialog.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Kirigami.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		src/.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		src/src/pycam.pro src/Gui/AboutDialog.h \
		src/Gui/dlgcuttersize.h \
		src/Gui/MainWindow.h \
		src/Gui/GLWidget.h \
		src/Gui/PreferencesDialog.h \
		src/Gui/StockModelDialog.h \
		src/Gui/ResizeModelDialog.h \
		src/Gui/AlignModelDialog.h \
		src/Gui/RotateModelDialog.h \
		src/Gui/SimpleCutterDialog.h src/pycam.cpp \
		src/Gui/dlgcuttersize.cpp \
		src/Gui/MainWindow.cpp \
		src/Gui/GLWidget.cpp \
		src/Gui/PreferencesDialog.cpp \
		src/Gui/StockModelDialog.cpp \
		src/Gui/ResizeModelDialog.cpp \
		src/Gui/AlignModelDialog.cpp \
		src/Gui/RotateModelDialog.cpp \
		src/Geometry/Geometry.cpp \
		src/Geometry/Boxed.cpp \
		src/Geometry/Stock.cpp \
		src/Geometry/Model.cpp \
		src/Geometry/Path.cpp \
		src/Geometry/HeightField.cpp \
		src/Geometry/TestModel.cpp \
		src/Utils/polynomials.cpp \
		src/Importers/STLImporter.cpp \
		src/Cutters/Cutter.cpp \
		src/Cutters/BaseCutter.cpp \
		src/Cutters/CylindricalCutter.cpp \
		src/Cutters/SphericalCutter.cpp \
		src/PathGenerators/DropCutter.cpp \
		src/PathGenerators/SimpleCutter.cpp \
		src/PathProcessors/PathProcessors.cpp \
		src/Exporters/GCodeExporter.cpp \
		src/Exporters/STLExporter.cpp \
		src/Tests/TestRunner.cpp
QMAKE_TARGET  = pycam
DESTDIR       = 
TARGET        = pycam


first: all
####### Build rules

$(TARGET): build/ui_MainWindow.h build/ui_AboutDialog.h build/ui_dlgcuttersize.h build/ui_PreferencesDialog.h build/ui_StockModelDialog.h build/ui_ResizeModelDialog.h build/ui_AlignModelDialog.h build/ui_RotateModelDialog.h build/ui_SimpleCutterDialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: src/pycam.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Kirigami.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		src/pycam.pro \
		src/Gui/pycam.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5OpenGL.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile src/pycam.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=qml_debug
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Kirigami.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_nfc.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
src/pycam.pro:
src/Gui/pycam.qrc:
/usr/lib/x86_64-linux-gnu/libQt5OpenGL.prl:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile src/pycam.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents src/Gui/pycam.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/Gui/AboutDialog.h src/Gui/dlgcuttersize.h src/Gui/MainWindow.h src/Gui/GLWidget.h src/Gui/PreferencesDialog.h src/Gui/StockModelDialog.h src/Gui/ResizeModelDialog.h src/Gui/AlignModelDialog.h src/Gui/RotateModelDialog.h src/Gui/SimpleCutterDialog.h $(DISTDIR)/
	$(COPY_FILE) --parents src/pycam.cpp src/Gui/dlgcuttersize.cpp src/Gui/MainWindow.cpp src/Gui/GLWidget.cpp src/Gui/PreferencesDialog.cpp src/Gui/StockModelDialog.cpp src/Gui/ResizeModelDialog.cpp src/Gui/AlignModelDialog.cpp src/Gui/RotateModelDialog.cpp src/Geometry/Geometry.cpp src/Geometry/Boxed.cpp src/Geometry/Stock.cpp src/Geometry/Model.cpp src/Geometry/Path.cpp src/Geometry/HeightField.cpp src/Geometry/TestModel.cpp src/Utils/polynomials.cpp src/Importers/STLImporter.cpp src/Cutters/Cutter.cpp src/Cutters/BaseCutter.cpp src/Cutters/CylindricalCutter.cpp src/Cutters/SphericalCutter.cpp src/PathGenerators/DropCutter.cpp src/PathGenerators/SimpleCutter.cpp src/PathProcessors/PathProcessors.cpp src/Exporters/GCodeExporter.cpp src/Exporters/STLExporter.cpp src/Tests/TestRunner.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/Gui/MainWindow.ui src/Gui/AboutDialog.ui src/Gui/dlgcuttersize.ui src/Gui/PreferencesDialog.ui src/Gui/StockModelDialog.ui src/Gui/ResizeModelDialog.ui src/Gui/AlignModelDialog.ui src/Gui/RotateModelDialog.ui src/Gui/SimpleCutterDialog.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: build/qrc_pycam.cpp
compiler_rcc_clean:
	-$(DEL_FILE) build/qrc_pycam.cpp
build/qrc_pycam.cpp: src/Gui/pycam.qrc \
		/usr/lib/qt5/bin/rcc \
		src/icons/logo_16px.png \
		src/icons/logo_gui.png \
		src/icons/logo_scalable.svg \
		src/icons/pycam.ico
	/usr/lib/qt5/bin/rcc -name pycam src/Gui/pycam.qrc -o build/qrc_pycam.cpp

compiler_moc_predefs_make_all: build/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) build/moc_predefs.h
build/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -m64 -pipe -g -Wall -W -dM -E -o build/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: build/moc_AboutDialog.cpp build/moc_dlgcuttersize.cpp build/moc_MainWindow.cpp build/moc_GLWidget.cpp build/moc_PreferencesDialog.cpp build/moc_StockModelDialog.cpp build/moc_ResizeModelDialog.cpp build/moc_AlignModelDialog.cpp build/moc_RotateModelDialog.cpp build/moc_SimpleCutterDialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_AboutDialog.cpp build/moc_dlgcuttersize.cpp build/moc_MainWindow.cpp build/moc_GLWidget.cpp build/moc_PreferencesDialog.cpp build/moc_StockModelDialog.cpp build/moc_ResizeModelDialog.cpp build/moc_AlignModelDialog.cpp build/moc_RotateModelDialog.cpp build/moc_SimpleCutterDialog.cpp
build/moc_AboutDialog.cpp: build/ui_AboutDialog.h \
		src/Gui/AboutDialog.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/data/projects/pycam/src -I/data/projects/pycam/src -I/data/projects/pycam/src/Gui -I/data/projects/pycam/src/Geometry -I/data/projects/pycam/src/Importers -I/data/projects/pycam/src/Cutters -I/data/projects/pycam/src/PathGenerators -I/data/projects/pycam/src/PathProcessors -I/data/projects/pycam/src/Exporters -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/Gui/AboutDialog.h -o build/moc_AboutDialog.cpp

build/moc_dlgcuttersize.cpp: src/Gui/dlgcuttersize.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/data/projects/pycam/src -I/data/projects/pycam/src -I/data/projects/pycam/src/Gui -I/data/projects/pycam/src/Geometry -I/data/projects/pycam/src/Importers -I/data/projects/pycam/src/Cutters -I/data/projects/pycam/src/PathGenerators -I/data/projects/pycam/src/PathProcessors -I/data/projects/pycam/src/Exporters -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/Gui/dlgcuttersize.h -o build/moc_dlgcuttersize.cpp

build/moc_MainWindow.cpp: build/ui_MainWindow.h \
		src/Gui/MainWindow.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/data/projects/pycam/src -I/data/projects/pycam/src -I/data/projects/pycam/src/Gui -I/data/projects/pycam/src/Geometry -I/data/projects/pycam/src/Importers -I/data/projects/pycam/src/Cutters -I/data/projects/pycam/src/PathGenerators -I/data/projects/pycam/src/PathProcessors -I/data/projects/pycam/src/Exporters -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/Gui/MainWindow.h -o build/moc_MainWindow.cpp

build/moc_GLWidget.cpp: src/Gui/GLWidget.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/data/projects/pycam/src -I/data/projects/pycam/src -I/data/projects/pycam/src/Gui -I/data/projects/pycam/src/Geometry -I/data/projects/pycam/src/Importers -I/data/projects/pycam/src/Cutters -I/data/projects/pycam/src/PathGenerators -I/data/projects/pycam/src/PathProcessors -I/data/projects/pycam/src/Exporters -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/Gui/GLWidget.h -o build/moc_GLWidget.cpp

build/moc_PreferencesDialog.cpp: build/ui_PreferencesDialog.h \
		src/Gui/PreferencesDialog.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/data/projects/pycam/src -I/data/projects/pycam/src -I/data/projects/pycam/src/Gui -I/data/projects/pycam/src/Geometry -I/data/projects/pycam/src/Importers -I/data/projects/pycam/src/Cutters -I/data/projects/pycam/src/PathGenerators -I/data/projects/pycam/src/PathProcessors -I/data/projects/pycam/src/Exporters -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/Gui/PreferencesDialog.h -o build/moc_PreferencesDialog.cpp

build/moc_StockModelDialog.cpp: build/ui_StockModelDialog.h \
		src/Gui/StockModelDialog.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/data/projects/pycam/src -I/data/projects/pycam/src -I/data/projects/pycam/src/Gui -I/data/projects/pycam/src/Geometry -I/data/projects/pycam/src/Importers -I/data/projects/pycam/src/Cutters -I/data/projects/pycam/src/PathGenerators -I/data/projects/pycam/src/PathProcessors -I/data/projects/pycam/src/Exporters -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/Gui/StockModelDialog.h -o build/moc_StockModelDialog.cpp

build/moc_ResizeModelDialog.cpp: build/ui_ResizeModelDialog.h \
		src/Gui/ResizeModelDialog.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/data/projects/pycam/src -I/data/projects/pycam/src -I/data/projects/pycam/src/Gui -I/data/projects/pycam/src/Geometry -I/data/projects/pycam/src/Importers -I/data/projects/pycam/src/Cutters -I/data/projects/pycam/src/PathGenerators -I/data/projects/pycam/src/PathProcessors -I/data/projects/pycam/src/Exporters -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/Gui/ResizeModelDialog.h -o build/moc_ResizeModelDialog.cpp

build/moc_AlignModelDialog.cpp: build/ui_AlignModelDialog.h \
		src/Gui/AlignModelDialog.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/data/projects/pycam/src -I/data/projects/pycam/src -I/data/projects/pycam/src/Gui -I/data/projects/pycam/src/Geometry -I/data/projects/pycam/src/Importers -I/data/projects/pycam/src/Cutters -I/data/projects/pycam/src/PathGenerators -I/data/projects/pycam/src/PathProcessors -I/data/projects/pycam/src/Exporters -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/Gui/AlignModelDialog.h -o build/moc_AlignModelDialog.cpp

build/moc_RotateModelDialog.cpp: build/ui_RotateModelDialog.h \
		src/Gui/RotateModelDialog.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/data/projects/pycam/src -I/data/projects/pycam/src -I/data/projects/pycam/src/Gui -I/data/projects/pycam/src/Geometry -I/data/projects/pycam/src/Importers -I/data/projects/pycam/src/Cutters -I/data/projects/pycam/src/PathGenerators -I/data/projects/pycam/src/PathProcessors -I/data/projects/pycam/src/Exporters -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/Gui/RotateModelDialog.h -o build/moc_RotateModelDialog.cpp

build/moc_SimpleCutterDialog.cpp: build/ui_SimpleCutterDialog.h \
		src/Gui/SimpleCutterDialog.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/data/projects/pycam/src -I/data/projects/pycam/src -I/data/projects/pycam/src/Gui -I/data/projects/pycam/src/Geometry -I/data/projects/pycam/src/Importers -I/data/projects/pycam/src/Cutters -I/data/projects/pycam/src/PathGenerators -I/data/projects/pycam/src/PathProcessors -I/data/projects/pycam/src/Exporters -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/Gui/SimpleCutterDialog.h -o build/moc_SimpleCutterDialog.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/ui_MainWindow.h build/ui_AboutDialog.h build/ui_dlgcuttersize.h build/ui_PreferencesDialog.h build/ui_StockModelDialog.h build/ui_ResizeModelDialog.h build/ui_AlignModelDialog.h build/ui_RotateModelDialog.h build/ui_SimpleCutterDialog.h
compiler_uic_clean:
	-$(DEL_FILE) build/ui_MainWindow.h build/ui_AboutDialog.h build/ui_dlgcuttersize.h build/ui_PreferencesDialog.h build/ui_StockModelDialog.h build/ui_ResizeModelDialog.h build/ui_AlignModelDialog.h build/ui_RotateModelDialog.h build/ui_SimpleCutterDialog.h
build/ui_MainWindow.h: src/Gui/MainWindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/Gui/MainWindow.ui -o build/ui_MainWindow.h

build/ui_AboutDialog.h: src/Gui/AboutDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/Gui/AboutDialog.ui -o build/ui_AboutDialog.h

build/ui_dlgcuttersize.h: src/Gui/dlgcuttersize.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/Gui/dlgcuttersize.ui -o build/ui_dlgcuttersize.h

build/ui_PreferencesDialog.h: src/Gui/PreferencesDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/Gui/PreferencesDialog.ui -o build/ui_PreferencesDialog.h

build/ui_StockModelDialog.h: src/Gui/StockModelDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/Gui/StockModelDialog.ui -o build/ui_StockModelDialog.h

build/ui_ResizeModelDialog.h: src/Gui/ResizeModelDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/Gui/ResizeModelDialog.ui -o build/ui_ResizeModelDialog.h

build/ui_AlignModelDialog.h: src/Gui/AlignModelDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/Gui/AlignModelDialog.ui -o build/ui_AlignModelDialog.h

build/ui_RotateModelDialog.h: src/Gui/RotateModelDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/Gui/RotateModelDialog.ui -o build/ui_RotateModelDialog.h

build/ui_SimpleCutterDialog.h: src/Gui/SimpleCutterDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/Gui/SimpleCutterDialog.ui -o build/ui_SimpleCutterDialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

build/pycam.o: src/pycam.cpp src/Gui/MainWindow.h \
		build/ui_MainWindow.h \
		src/Geometry/Stock.h \
		src/Geometry/Boxed.h \
		src/Geometry/Model.h \
		src/Geometry/Geometry.h \
		src/Geometry/Point.h \
		src/Geometry/Edge.h \
		src/Geometry/Triangle.h \
		src/Geometry/Path.h \
		src/Cutters/Cutter.h \
		src/Geometry/HeightField.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/pycam.o src/pycam.cpp

build/dlgcuttersize.o: src/Gui/dlgcuttersize.cpp src/Gui/dlgcuttersize.h \
		build/ui_dlgcuttersize.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/dlgcuttersize.o src/Gui/dlgcuttersize.cpp

build/MainWindow.o: src/Gui/MainWindow.cpp src/Gui/MainWindow.h \
		build/ui_MainWindow.h \
		src/Gui/GLWidget.h \
		src/Gui/AboutDialog.h \
		build/ui_AboutDialog.h \
		src/Gui/PreferencesDialog.h \
		build/ui_PreferencesDialog.h \
		src/Gui/StockModelDialog.h \
		build/ui_StockModelDialog.h \
		src/Gui/ResizeModelDialog.h \
		build/ui_ResizeModelDialog.h \
		src/Gui/AlignModelDialog.h \
		build/ui_AlignModelDialog.h \
		src/Gui/RotateModelDialog.h \
		build/ui_RotateModelDialog.h \
		src/Gui/SimpleCutterDialog.h \
		build/ui_SimpleCutterDialog.h \
		src/Gui/dlgcuttersize.h \
		src/Geometry/Stock.h \
		src/Geometry/Boxed.h \
		src/Geometry/Model.h \
		src/Geometry/Geometry.h \
		src/Geometry/Point.h \
		src/Geometry/Edge.h \
		src/Geometry/Triangle.h \
		src/Geometry/Path.h \
		src/Cutters/Cutter.h \
		src/PathGenerators/DropCutter.h \
		src/Geometry/HeightField.h \
		src/PathGenerators/SimpleCutter.h \
		src/Geometry/TestModel.h \
		src/Importers/STLImporter.h \
		src/Exporters/GCodeExporter.h \
		src/Exporters/STLExporter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/MainWindow.o src/Gui/MainWindow.cpp

build/GLWidget.o: src/Gui/GLWidget.cpp src/Gui/GLWidget.h \
		src/Geometry/TestModel.h \
		src/Geometry/Model.h \
		src/Geometry/Geometry.h \
		src/Geometry/Point.h \
		src/Geometry/Edge.h \
		src/Geometry/Triangle.h \
		src/Geometry/Boxed.h \
		src/Importers/STLImporter.h \
		src/Cutters/Cutter.h \
		src/Geometry/Path.h \
		src/Geometry/Stock.h \
		src/Geometry/HeightField.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/GLWidget.o src/Gui/GLWidget.cpp

build/PreferencesDialog.o: src/Gui/PreferencesDialog.cpp src/Gui/PreferencesDialog.h \
		build/ui_PreferencesDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/PreferencesDialog.o src/Gui/PreferencesDialog.cpp

build/StockModelDialog.o: src/Gui/StockModelDialog.cpp src/Gui/StockModelDialog.h \
		build/ui_StockModelDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/StockModelDialog.o src/Gui/StockModelDialog.cpp

build/ResizeModelDialog.o: src/Gui/ResizeModelDialog.cpp src/Gui/ResizeModelDialog.h \
		build/ui_ResizeModelDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/ResizeModelDialog.o src/Gui/ResizeModelDialog.cpp

build/AlignModelDialog.o: src/Gui/AlignModelDialog.cpp src/Gui/AlignModelDialog.h \
		build/ui_AlignModelDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/AlignModelDialog.o src/Gui/AlignModelDialog.cpp

build/RotateModelDialog.o: src/Gui/RotateModelDialog.cpp src/Gui/RotateModelDialog.h \
		build/ui_RotateModelDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/RotateModelDialog.o src/Gui/RotateModelDialog.cpp

build/Geometry.o: src/Geometry/Geometry.cpp src/Geometry/Geometry.h \
		src/Geometry/Point.h \
		src/Geometry/Edge.h \
		src/Geometry/Triangle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Geometry.o src/Geometry/Geometry.cpp

build/Boxed.o: src/Geometry/Boxed.cpp src/Geometry/Boxed.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Boxed.o src/Geometry/Boxed.cpp

build/Stock.o: src/Geometry/Stock.cpp src/Geometry/Stock.h \
		src/Geometry/Boxed.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Stock.o src/Geometry/Stock.cpp

build/Model.o: src/Geometry/Model.cpp src/Geometry/Model.h \
		src/Geometry/Geometry.h \
		src/Geometry/Point.h \
		src/Geometry/Edge.h \
		src/Geometry/Triangle.h \
		src/Geometry/Boxed.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Model.o src/Geometry/Model.cpp

build/Path.o: src/Geometry/Path.cpp src/Geometry/Path.h \
		src/Geometry/Point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Path.o src/Geometry/Path.cpp

build/HeightField.o: src/Geometry/HeightField.cpp src/Geometry/HeightField.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/HeightField.o src/Geometry/HeightField.cpp

build/TestModel.o: src/Geometry/TestModel.cpp src/Geometry/TestModel.h \
		src/Geometry/Model.h \
		src/Geometry/Geometry.h \
		src/Geometry/Point.h \
		src/Geometry/Edge.h \
		src/Geometry/Triangle.h \
		src/Geometry/Boxed.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/TestModel.o src/Geometry/TestModel.cpp

build/polynomials.o: src/Utils/polynomials.cpp src/Utils/polynomials.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/polynomials.o src/Utils/polynomials.cpp

build/STLImporter.o: src/Importers/STLImporter.cpp src/Importers/STLImporter.h \
		src/Geometry/Model.h \
		src/Geometry/Geometry.h \
		src/Geometry/Point.h \
		src/Geometry/Edge.h \
		src/Geometry/Triangle.h \
		src/Geometry/Boxed.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/STLImporter.o src/Importers/STLImporter.cpp

build/Cutter.o: src/Cutters/Cutter.cpp src/Cutters/Cutter.h \
		src/Geometry/Geometry.h \
		src/Geometry/Point.h \
		src/Geometry/Edge.h \
		src/Geometry/Triangle.h \
		src/Geometry/Model.h \
		src/Geometry/Boxed.h \
		src/Cutters/SphericalCutter.h \
		src/Cutters/BaseCutter.h \
		src/Geometry/intersection.h \
		src/Utils/polynomials.h \
		src/Cutters/CylindricalCutter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Cutter.o src/Cutters/Cutter.cpp

build/BaseCutter.o: src/Cutters/BaseCutter.cpp src/Cutters/BaseCutter.h \
		src/Cutters/Cutter.h \
		src/Geometry/Geometry.h \
		src/Geometry/Point.h \
		src/Geometry/Edge.h \
		src/Geometry/Triangle.h \
		src/Geometry/Model.h \
		src/Geometry/Boxed.h \
		src/Geometry/intersection.h \
		src/Utils/polynomials.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/BaseCutter.o src/Cutters/BaseCutter.cpp

build/CylindricalCutter.o: src/Cutters/CylindricalCutter.cpp src/Cutters/CylindricalCutter.h \
		src/Cutters/BaseCutter.h \
		src/Cutters/Cutter.h \
		src/Geometry/Geometry.h \
		src/Geometry/Point.h \
		src/Geometry/Edge.h \
		src/Geometry/Triangle.h \
		src/Geometry/Model.h \
		src/Geometry/Boxed.h \
		src/Geometry/intersection.h \
		src/Utils/polynomials.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/CylindricalCutter.o src/Cutters/CylindricalCutter.cpp

build/SphericalCutter.o: src/Cutters/SphericalCutter.cpp src/Cutters/SphericalCutter.h \
		src/Cutters/BaseCutter.h \
		src/Cutters/Cutter.h \
		src/Geometry/Geometry.h \
		src/Geometry/Point.h \
		src/Geometry/Edge.h \
		src/Geometry/Triangle.h \
		src/Geometry/Model.h \
		src/Geometry/Boxed.h \
		src/Geometry/intersection.h \
		src/Utils/polynomials.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/SphericalCutter.o src/Cutters/SphericalCutter.cpp

build/DropCutter.o: src/PathGenerators/DropCutter.cpp src/PathGenerators/DropCutter.h \
		src/Cutters/Cutter.h \
		src/Geometry/Geometry.h \
		src/Geometry/Point.h \
		src/Geometry/Edge.h \
		src/Geometry/Triangle.h \
		src/Geometry/Model.h \
		src/Geometry/Boxed.h \
		src/Geometry/HeightField.h \
		src/PathProcessors/PathProcessors.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/DropCutter.o src/PathGenerators/DropCutter.cpp

build/SimpleCutter.o: src/PathGenerators/SimpleCutter.cpp src/PathGenerators/SimpleCutter.h \
		src/Geometry/Path.h \
		src/Geometry/Point.h \
		src/Geometry/HeightField.h \
		src/PathProcessors/PathProcessors.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/SimpleCutter.o src/PathGenerators/SimpleCutter.cpp

build/PathProcessors.o: src/PathProcessors/PathProcessors.cpp src/PathProcessors/PathProcessors.h \
		src/Geometry/Path.h \
		src/Geometry/Point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/PathProcessors.o src/PathProcessors/PathProcessors.cpp

build/GCodeExporter.o: src/Exporters/GCodeExporter.cpp src/Exporters/GCodeExporter.h \
		src/Geometry/Path.h \
		src/Geometry/Point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/GCodeExporter.o src/Exporters/GCodeExporter.cpp

build/STLExporter.o: src/Exporters/STLExporter.cpp src/Exporters/STLExporter.h \
		src/Geometry/Model.h \
		src/Geometry/Geometry.h \
		src/Geometry/Point.h \
		src/Geometry/Edge.h \
		src/Geometry/Triangle.h \
		src/Geometry/Boxed.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/STLExporter.o src/Exporters/STLExporter.cpp

build/TestRunner.o: src/Tests/TestRunner.cpp src/Geometry/Model.h \
		src/Geometry/Geometry.h \
		src/Geometry/Point.h \
		src/Geometry/Edge.h \
		src/Geometry/Triangle.h \
		src/Geometry/Boxed.h \
		src/Geometry/TestModel.h \
		src/Cutters/CylindricalCutter.h \
		src/Cutters/BaseCutter.h \
		src/Cutters/Cutter.h \
		src/Geometry/intersection.h \
		src/Utils/polynomials.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/TestRunner.o src/Tests/TestRunner.cpp

build/qrc_pycam.o: build/qrc_pycam.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/qrc_pycam.o build/qrc_pycam.cpp

build/moc_AboutDialog.o: build/moc_AboutDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_AboutDialog.o build/moc_AboutDialog.cpp

build/moc_dlgcuttersize.o: build/moc_dlgcuttersize.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_dlgcuttersize.o build/moc_dlgcuttersize.cpp

build/moc_MainWindow.o: build/moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_MainWindow.o build/moc_MainWindow.cpp

build/moc_GLWidget.o: build/moc_GLWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_GLWidget.o build/moc_GLWidget.cpp

build/moc_PreferencesDialog.o: build/moc_PreferencesDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_PreferencesDialog.o build/moc_PreferencesDialog.cpp

build/moc_StockModelDialog.o: build/moc_StockModelDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_StockModelDialog.o build/moc_StockModelDialog.cpp

build/moc_ResizeModelDialog.o: build/moc_ResizeModelDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_ResizeModelDialog.o build/moc_ResizeModelDialog.cpp

build/moc_AlignModelDialog.o: build/moc_AlignModelDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_AlignModelDialog.o build/moc_AlignModelDialog.cpp

build/moc_RotateModelDialog.o: build/moc_RotateModelDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_RotateModelDialog.o build/moc_RotateModelDialog.cpp

build/moc_SimpleCutterDialog.o: build/moc_SimpleCutterDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_SimpleCutterDialog.o build/moc_SimpleCutterDialog.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

